# Build stage
FROM node:18-alpine AS build

WORKDIR /app

# Define build arguments for public env variables
ARG VITE_AI_PROVIDER
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_STRIPE_PRICE_PRO_MONTHLY
ARG VITE_STRIPE_PRICE_BUSINESS_MONTHLY
ARG VITE_STRIPE_PRICE_ENTERPRISE_MONTHLY

# Set them as environment variables for the build
ENV VITE_AI_PROVIDER=$VITE_AI_PROVIDER
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_STRIPE_PRICE_PRO_MONTHLY=$VITE_STRIPE_PRICE_PRO_MONTHLY
ENV VITE_STRIPE_PRICE_BUSINESS_MONTHLY=$VITE_STRIPE_PRICE_BUSINESS_MONTHLY
ENV VITE_STRIPE_PRICE_ENTERPRISE_MONTHLY=$VITE_STRIPE_PRICE_ENTERPRISE_MONTHLY

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Production stage
FROM nginx:1.21.3-alpine AS production

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
